CREATE TABLE [dbo].[Product]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(150) NOT NULL,
	[BrandId] INT NOT NULL,
	[EAN13] CHAR(13) NOT NULL, 
	[Price] DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_Product_Brand FOREIGN KEY(BrandId) REFERENCES Brand(Id),
	CONSTRAINT UK_Product_EAN UNIQUE(EAN13)
)
